version: '3'

services:
  lenses:
    image: lensesio/box
    container_name: lenses
    restart: always
    environment:
      EULA: "${LICENSE}"
    networks:
      - lenses-box
    ports:
      - 3030:3030

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - lenses-box
    ports:
     - 8080:8080
     - 50000:50000

networks:
  lenses-box:
    driver: bridge

